import { useEffect, useRef } from 'react';
import type { LeafletMouseEvent } from 'leaflet';
import L from 'leaflet';
import { MapContainer, TileLayer, Rectangle, Tooltip, CircleMarker, Marker, useMap, useMapEvents } from 'react-leaflet';
import { statusColor, statusFill, SIGNAL } from '../api';
import type { AdminAmbulanceMarker, AdminCampMarker, AdminInjuredPersonMarker, AdminSecurityMarker, AttendeeMarker, CasualtyMarker, PanicPing, Responder, UploadedReportMarker, Zone } from '../models';
const SATELLITE_TILES='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}';
const SATELLITE_ATTRIBUTION='Tiles &copy; Esri &mdash; Source: Esri, Maxar, Earthstar Geographics';
const campIcon = L.divIcon({ className: '', html: '<div style="display:flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:9999px;background:#facc15;color:#1f2937;font-size:15px;line-height:1;box-shadow:0 0 8px rgba(250,204,21,0.8);">★</div>', iconSize: [18,18], iconAnchor: [9,9] });
function ClickToSetLocation({onMapClick}:{onMapClick:(lat:number,lng:number)=>void}){useMapEvents({click:(e: LeafletMouseEvent)=>onMapClick(e.latlng.lat,e.latlng.lng)});return null}
function ZoneRectangle({zone}:{zone:Zone}){const layerRef=useRef<any>(null);useEffect(()=>{const layer=layerRef.current;const el=layer?.getElement?.()||layer?._path;if(el)el.classList.toggle('zone-critical-pulse',zone.status==='critical')},[zone.status]);const [minLat,minLng,maxLat,maxLng]=zone.bounds;return <Rectangle ref={layerRef} bounds={[[minLat,minLng],[maxLat,maxLng]]} pathOptions={{color:statusColor(zone.status),weight:1.5,fillColor:statusFill(zone.status),fillOpacity:.55}}><Tooltip permanent direction="center" className="zone-label">{zone.name}<br/>{zone.count}/{zone.cap} ({zone.pct}%)</Tooltip></Rectangle>}
function PanicMarkers({panicPings}:{panicPings:PanicPing[]}){return <>{panicPings.map(p=><CircleMarker key={p.id} center={[p.lat,p.lng]} radius={7} pathOptions={{color:'#E0A83E',fillColor:'#E0A83E',fillOpacity:.7,weight:1.5}}><Tooltip>Panic report</Tooltip></CircleMarker>)}</>}
function CasualtyMarkers({casualties,onCasualtyClick}:{casualties:CasualtyMarker[];onCasualtyClick:(marker:CasualtyMarker)=>void}){return <>{casualties.map(c=>{const fillColor = c.severity==='red' ? '#ef4444' : c.severity==='yellow' ? '#facc15' : '#4ade80'; const label = c.severity==='red' ? 'Critical casualty' : c.severity==='yellow' ? 'Monitoring' : 'Minor casualty'; return <CircleMarker key={c.id} center={[c.lat,c.lng]} radius={9} pathOptions={{color:fillColor,fillColor,fillOpacity:.88,weight:2}} eventHandlers={{click:()=>onCasualtyClick(c)}}><Tooltip>{c.zoneName} · {label}<br/>{c.hospitalCamp || 'Nearby camp'} · {c.ambulanceEtaMinutes ?? 7} min</Tooltip></CircleMarker>;})}</>}
function CampMarkers({camps}:{camps:AdminCampMarker[]}){return <>{camps.map(camp => <Marker key={camp.id} position={[camp.lat,camp.lng]} icon={campIcon}><Tooltip>{camp.name}</Tooltip></Marker>)}</>}
function SecurityMarkers({security}:{security:AdminSecurityMarker[]}){return <>{security.map(unit=><CircleMarker key={unit.id} center={[unit.lat,unit.lng]} radius={6} pathOptions={{color:'#22c55e',fillColor:'#22c55e',fillOpacity:.85,weight:1.5}}><Tooltip>{unit.name} · {unit.status}</Tooltip></CircleMarker>)}</>}
function AmbulanceMarkers({ambulances}:{ambulances:AdminAmbulanceMarker[]}){return <>{ambulances.map(unit=><CircleMarker key={unit.id} center={[unit.lat,unit.lng]} radius={7} pathOptions={{color:'#38bdf8',fillColor:'#38bdf8',fillOpacity:.8,weight:1.6}}><Tooltip>{unit.name}<br/>ETA {unit.etaMinutes} min · {unit.routeTo}</Tooltip></CircleMarker>)}</>}
function InjuredPersonMarkers({persons}:{persons:AdminInjuredPersonMarker[]}){return <>{persons.map(person=><CircleMarker key={person.id} center={[person.lat,person.lng]} radius={5} pathOptions={{color: person.severity === 'red' ? '#f87171' : person.severity === 'yellow' ? '#fbbf24' : '#4ade80', fillColor: person.severity === 'red' ? '#f87171' : person.severity === 'yellow' ? '#fbbf24' : '#4ade80', fillOpacity:0.9, weight:1.2}}><Tooltip>{person.label} · {person.casualtyZone}</Tooltip></CircleMarker>)}</>}
function UploadedReportMarkers({reports}:{reports:UploadedReportMarker[]}){return <>{reports.map(report => <CircleMarker key={report.id} center={[report.latitude, report.longitude]} radius={8} pathOptions={{color:'#f472b6', fillColor:'#f472b6', fillOpacity:0.9, weight:2}}><Tooltip>{report.reporterName}<br/>{report.zoneName || 'Uploaded location'}<br/>{report.severity || 'Medium'} severity</Tooltip></CircleMarker>)}</>}
function FitOnce({center}:{center:[number,number]}){const map=useMap();useEffect(()=>{map.setView(center,17,{animate:true,duration:.65})},[map,center]);return null}
interface Props {venueCenter:[number,number];zones:Zone[];responders:Responder[];panicPings:PanicPing[];casualties:CasualtyMarker[];camps:AdminCampMarker[];security:AdminSecurityMarker[];ambulances:AdminAmbulanceMarker[];injuredPersons:AdminInjuredPersonMarker[];reportMarkers:UploadedReportMarker[];attendeeMarker:AttendeeMarker|null;onMapClick:(lat:number,lng:number)=>void;onCasualtyClick:(marker:CasualtyMarker)=>void}
export default function MapView({venueCenter,zones,responders,panicPings,casualties,camps,security,ambulances,injuredPersons,reportMarkers,attendeeMarker,onMapClick,onCasualtyClick}:Props){return <div className="h-full w-full"><MapContainer center={venueCenter} zoom={17} style={{width:'100%',height:'100%'}} attributionControl><FitOnce center={venueCenter}/><TileLayer url={SATELLITE_TILES} attribution={SATELLITE_ATTRIBUTION} maxZoom={19}/><ClickToSetLocation onMapClick={onMapClick}/>{zones.map(z=><ZoneRectangle key={z.id} zone={z}/>)}{responders.map(r=><CircleMarker key={r.id} center={[r.lat,r.lng]} radius={6} pathOptions={{color:r.status==='dispatched'?statusColor('critical'):SIGNAL,fillColor:r.status==='dispatched'?statusColor('critical'):SIGNAL,fillOpacity:.9,weight:1.5}}><Tooltip>{r.name} · {r.status}</Tooltip></CircleMarker>)}<PanicMarkers panicPings={panicPings}/><CasualtyMarkers casualties={casualties} onCasualtyClick={onCasualtyClick}/><CampMarkers camps={camps}/><SecurityMarkers security={security}/><AmbulanceMarkers ambulances={ambulances}/><InjuredPersonMarkers persons={injuredPersons}/><UploadedReportMarkers reports={reportMarkers}/>{attendeeMarker&&<CircleMarker center={[attendeeMarker.lat,attendeeMarker.lng]} radius={8} pathOptions={{color:'#FFFFFF',fillColor:SIGNAL,fillOpacity:1,weight:2}}><Tooltip permanent>You are here</Tooltip></CircleMarker>}</MapContainer></div>}
